Feature 3 webinarframe
meister-highschool-webinar/front-app pull request #20
Opened 2020-08-23 23:44 UTC by SoonGwan

store/repository에서 받아 store에서 observable로 따로 빼와서 작업을 하였습니다.
현재 타임테이블에 날짜를 표시해주는 것은 맨 timetable에 0번째 배열을 들고와서 날짜를 표시해주고 있습니다.
시간 계산 하는 부분을 코드를 간결하게 짜고 싶습니다. ㅠ

2020-08-24 01:24 UTC, zerone2 commented
```
 const timeTableListMap =
    timeTableList &&
    timeTableList.map((data) => {
      const { start_time, end_time, speech, track_name } = data
      const start_time_min = new Date(start_time).getMinutes()
      const end_time_min = new Date(end_time).getMinutes()
      const start_time_hour = new Date(start_time).getHours()
      const end_time_hour = new Date(end_time).getHours()
      const min_result = end_time_min - start_time_min
      const hour_result = (end_time_hour - start_time_hour) * 60
      const time_result = hour_result + min_result

      return (
        <>
          <tr>
            <TimeTableTemp art_time={start_time} end_time={end_time} speech={speech} track_name={track_name} result={time_result} />
          </tr>
        </>
      )
    })
```
코드 간결하게 짜고 싶다는 부분이 이 부분 말씀하시는건가요?? moment api doc 보시면 시간 계산하는 메소드가 있으니 참고해보시고 잘 안되시면 다시 말씀해주세요 ㅎㅎ

2020-08-24 02:27 UTC, SoonGwan commented
듀레이션으로 계산 하니까 Nan이 떴어서요

2020-08-24 03:23 UTC, zerone2 commented
new Date 말고 moment로 받아봤어요?

2020-08-24 04:14 UTC, SoonGwan commented
duration 사용해서 수정했습니다.

2020-08-24 06:11 UTC, SoonGwan commented
Promise 를 사용하지않고 async함수를 이용하여 promise를 같이 return 해주도록 하기 위해 리펙토링을 진행하였습니다.

2020-08-24 12:30 UTC, zerone2 commented
고생하셨어요 ㅎㅎ

2020-08-24 12:38 UTC, zerone2 requested changes
api 관련코드들 apis.js 로 빼주세요~ store 쪽에서 api 처리해도 되지만 api들은 왠만하면 한곳에 모아놓는게 나중에 리팩토링을 할 때에도 좋을 것 같아요~

2020-08-24 12:38 UTC, zerone2 commented on src/stores/WebinarTimeTableStore/WebinarTimeTableRepository.js
> +export default new WebinarTimeTableRepository()
이 부분은 apis.js 안으로 넣어주시겠어요 ?

2020-08-24 12:38 UTC, zerone2 commented on src/stores/WebinarInfoStore/WebinarInfoRepository.js
> +export default new WebinarInfoRepository()
이 부분도 apis.js 로 넣어주시겠어요? apis.js하고 axios.js 코드 확인해보시면 대충 어떻게 넣어야되는데 감이 오실거에요.

2020-08-24 12:38 UTC, zerone2 commented on src/stores/WebinarInfoStore/WebinarInfoStore.js
> +export default WebinarInfoStore
api 코드 apis.js 로 빼주시고 이쪽 코드도 같이 수정해주세요 :)

2020-08-26 05:11 UTC, SoonGwan commented on src/stores/WebinarInfoStore/WebinarInfoStore.js
> +export default WebinarInfoStore
넵 수정하였습니다.

2020-08-26 05:14 UTC, SoonGwan commented on src/stores/WebinarTimeTableStore/WebinarTimeTableRepository.js
> +export default new WebinarTimeTableRepository()
네 수정하였습니다.

2020-08-26 05:14 UTC, SoonGwan commented on src/stores/WebinarInfoStore/WebinarInfoRepository.js
> +export default new WebinarInfoRepository()
네 수정하였습니다.

2020-08-27 10:36 UTC, zerone2 commented
충돌이 나서 제가 수정할꺼 하면서 병합했는데 혹시 모르니까 한번 더 테스트하면서 확인부탁해요 :)

2020-08-27 11:09 UTC, SoonGwan commented
오류나는 부분 수정하여 테스트 하였습니다.

2020-08-28 00:34 UTC, zerone2 commented
고생하셨습니다.

2020-08-28 00:34 UTC, merged

2020-08-28 01:08 UTC, zerone2 commented
순관님 테스트 해보셨으면 원래대로 돌려놔야죠... 본인맘대로 다른 사람이 짠 코드를 주석처리 해놓으면 코드 전체가 꼬일 수가 있습니다. 본인 것만 테스트해보고 그대로 올리셔야 됩니다.