[ADD] luckydraw
meister-highschool-webinar/front-app pull request #25
Opened 2020-08-26 05:57 UTC by hyejun0608

소켓 연동 해봤습니다..!

2020-08-28 01:02 UTC, zerone2 requested changes
전체적으로 코드가 정리가 덜 된 느낌이에요. 혹시 테스트는 해보셨나요? 이대로 하셨으면 정상동작 안했을텐데 테스트는 해보고 올려주세요.

2020-08-28 01:02 UTC, zerone2 commented on src/components/LuckyDraw/LuckyDraw.js
> +            </div>
이 부분은 반복되는 부분이 많으니 조금 줄일 수 있겠네요. 
style은 자바스크립트랑 맞물려서 바뀌는 스타일이 아닌이상 scss 파일안에 넣어주세요 ~
```
.table__list {
  background-color: rgb(153, 153, 153);
  & > div {
    flex: 1;
    &:nth-child(2) {
      flex: 2;
    }
  }
}
```
정확하게 동작할지는 모르겠지만 대략 이런식으로 scss 작업해주시면 js쪽 스타일 코드 없앨 수 있겠죠?
```
<div style={{ flex: 1 }}>
  <span style={{ color: "white" }}>번호</span>
</div>
```
그리고 이부분은 중복되니까 코드를 줄여주면 좋을 것 같아요.
위에다가 따로 컴포넌트를 생성한다음에 불러와서 써주면 좋을 것 같아요.

2020-08-28 01:02 UTC, zerone2 commented on src/components/LuckyDraw/LuckyDraw.js
> +            {data.map((item, ix) => {
여기있는 item이 어디서 가져오는지 모르겠네요.

2020-08-29 05:00 UTC, kyoungsik-dev commented
- 혜준님, 우리가 하는 일은 웨비나 플랫폼이라는 하나의 제품을 만드는 것입니다. PR을 보내는 건 제품의 여러 기능 중에서, 본인이 담당한 기능의 개발을 완료하였으니 이를 확인해달라는 것이고요.
- 그런데 지금 혜준님께서는 지금 해당 기능의 개발을 완료했다고 말씀해주실 수 있나요?
  - 혜준님 브랜치를 받아서 직접 실행시켜보고, socket 연동을 테스트해보기 위해 Backend 서버도 띄워봤습니다. 그런데 전혀 동작을 하지 않습니다.
  - 코드를 찾아보니 애초에 `LuckyDraw` 컴포넌트가 서비스에 붙어있지도 않더군요. 그래서 제가 직접 붙여서 테스트 해봤는데, 그래도 오류만 발생합니다.
  - socket.io-client 라이브러리는 `package.json`에 추가도 되어있지 않습니다. npm install socket.io-client 자체를 안하신 건 아닌지요? 해당 라이브러리가 없으면 실행 자체가 안될텐데요.
  - Backend의 서버 기본 포트는 3000번인데, 코드에는 왜 4000번으로 되어있는지도 의뭉스럽습니다.
- 코드에 미비한 부분이 있거나, 비효율적이거나, 로직에 문제가 있거나, 그런 부분들은 다 괜찮습니다. 그건 천천히 고쳐나가면 되니까요. 그러나 본인이 담당한 부분에 대해서는 책임지고 완성을 해야 합니다. 지금 PR은 close 해주시고요, 개발을 완료해주신 이후에 다시 PR 올려주시면 감사하겠습니다. 질문은 언제든지 환영합니다.🙏

2020-08-29 05:05 UTC, closed without merging